version: '3'
networks:
  nestjs-mod-engine-network:
    driver: 'bridge'
services:
  nestjs-mod-engine-postgre-sql:
    image: 'bitnami/postgresql:15.5.0'
    container_name: 'nestjs-mod-engine-postgre-sql'
    networks:
      - 'nestjs-mod-engine-network'
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U postgres'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
    environment:
      POSTGRESQL_USERNAME: '%RUCKEN_POSTGRE_SQL_POSTGRESQL_USERNAME%'
      POSTGRESQL_PASSWORD: '%RUCKEN_POSTGRE_SQL_POSTGRESQL_PASSWORD%'
      POSTGRESQL_DATABASE: '%RUCKEN_POSTGRE_SQL_POSTGRESQL_DATABASE%'
    volumes:
      - 'nestjs-mod-engine-postgre-sql-volume:/bitnami/postgresql'
volumes:
  nestjs-mod-engine-postgre-sql-volume:
    external: true
    name: 'nestjs-mod-engine-postgre-sql-volume'
