version: '3'
networks:
  nestjs-mod-engine-network:
    driver: 'bridge'
services:
  nestjs-mod-engine-postgre-sql:
    image: 'bitnami/postgresql:15.5.0'
    container_name: 'nestjs-mod-engine-postgre-sql'
    networks:
      - 'nestjs-mod-engine-network'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U postgres'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
    environment:
      POSTGRESQL_USERNAME: '${RUCKEN_POSTGRE_SQL_POSTGRESQL_USERNAME}'
      POSTGRESQL_PASSWORD: '${RUCKEN_POSTGRE_SQL_POSTGRESQL_PASSWORD}'
      POSTGRESQL_DATABASE: '${RUCKEN_POSTGRE_SQL_POSTGRESQL_DATABASE}'
    volumes:
      - 'nestjs-mod-engine-postgre-sql-volume:/bitnami/postgresql'
  nestjs-mod-engine-minio:
    image: 'bitnami/minio:2024.11.7'
    container_name: 'nestjs-mod-engine-minio'
    volumes:
      - 'nestjs-mod-engine-minio-volume:/bitnami/minio/data'
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - 'nestjs-mod-engine-network'
    environment:
      MINIO_ROOT_USER: '${RUCKEN_MINIO_MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${RUCKEN_MINIO_MINIO_ROOT_PASSWORD}'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'mc'
        - 'ready'
        - 'local'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
  nestjs-mod-engine-redis:
    image: 'bitnami/redis:7.4.1'
    container_name: 'nestjs-mod-engine-redis'
    volumes:
      - 'nestjs-mod-engine-redis-volume:/bitnami/redis/data'
    ports:
      - '6379:6379'
    networks:
      - 'nestjs-mod-engine-network'
    environment:
      REDIS_DATABASE: '0'
      REDIS_PASSWORD: '${RUCKEN_REDIS_REDIS_PASSWORD}'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'redis-cli --no-auth-warning -a $$REDIS_PASSWORD ping | grep PONG'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
  nestjs-mod-engine-server:
    image: nestjs-mod-engine
    build:
      dockerfile: ./.docker/server.Dockerfile
      context: ..
    container_name: 'nestjs-mod-engine-server'
    ports:
      - '${RUCKEN_PORT}:${RUCKEN_PORT}'
    networks:
      - 'nestjs-mod-engine-network'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          './node_modules/.bin/wait-on --timeout= --interval=1000 --window --verbose --log http://localhost:${RUCKEN_PORT}/api/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 10
    tty: true
    environment:
      ENV COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      RUCKEN_PORT: '${RUCKEN_PORT}'
      RUCKEN_ENGINE_ADMIN_SECRET: '${RUCKEN_ENGINE_ADMIN_SECRET}'
      RUCKEN_WEBHOOK_DATABASE_URL: '${RUCKEN_WEBHOOK_DATABASE_URL}'
      RUCKEN_ENGINE_DATABASE_URL: '${RUCKEN_ENGINE_DATABASE_URL}'
      RUCKEN_NOTIFICATIONS_DATABASE_URL: '${RUCKEN_NOTIFICATIONS_DATABASE_URL}'
      RUCKEN_TWO_FACTOR_DATABASE_URL: '${RUCKEN_TWO_FACTOR_DATABASE_URL}'
      RUCKEN_ENGINE_ADMIN_EMAIL: '${RUCKEN_ENGINE_ADMIN_EMAIL}'
      RUCKEN_ENGINE_ADMIN_USERNAME: '${RUCKEN_ENGINE_ADMIN_USERNAME}'
      RUCKEN_ENGINE_ADMIN_PASSWORD: '${RUCKEN_ENGINE_ADMIN_PASSWORD}'
      RUCKEN_MINIO_SERVER_HOST: '${RUCKEN_MINIO_SERVER_HOST}'
      RUCKEN_MINIO_ACCESS_KEY: '${RUCKEN_MINIO_ACCESS_KEY}'
      RUCKEN_MINIO_SECRET_KEY: '${RUCKEN_MINIO_SECRET_KEY}'
      RUCKEN_KEYV_URL: '${RUCKEN_KEYV_URL}'
      RUCKEN_ENGINE_SERVER_URL: '${RUCKEN_ENGINE_SERVER_URL}'
      RUCKEN_ENGINE_JWT_ACCESS_TOKEN_EXPIRES_IN: '${RUCKEN_ENGINE_JWT_ACCESS_TOKEN_EXPIRES_IN}'
      RUCKEN_ENGINE_JWT_REFRESH_TOKEN_EXPIRES_IN: '${RUCKEN_ENGINE_JWT_REFRESH_TOKEN_EXPIRES_IN}'
      RUCKEN_ENGINE_DEFAULT_PUBLIC_PROJECTS: '${RUCKEN_ENGINE_DEFAULT_PUBLIC_PROJECTS}'
      RUCKEN_ENGINE_DEFAULT_PROJECT: '${RUCKEN_ENGINE_DEFAULT_PROJECT}'
      RUCKEN_ROOT_DATABASE_URL: '${RUCKEN_ROOT_DATABASE_URL}'
      RUCKEN_ENGINE_CLIENT_URL: '${RUCKEN_ENGINE_CLIENT_URL}'
      RUCKEN_ENGINE_GOOGLE_OAUTH_CLIENT_ID: '${RUCKEN_ENGINE_GOOGLE_OAUTH_CLIENT_ID}'
      RUCKEN_ENGINE_GOOGLE_OAUTH_CLIENT_SECRET_KEY: '${RUCKEN_ENGINE_GOOGLE_OAUTH_CLIENT_SECRET_KEY}'
      RUCKEN_CLIENT_MINIO_URL: '${RUCKEN_CLIENT_MINIO_URL}'
    restart: 'always'
    depends_on:
      nestjs-mod-engine-minio:
        condition: 'service_started'
      nestjs-mod-engine-redis:
        condition: 'service_healthy'
      nestjs-mod-engine-postgre-sql:
        condition: service_healthy
volumes:
  nestjs-mod-engine-postgre-sql-volume:
    name: 'nestjs-mod-engine-postgre-sql-volume'
  nestjs-mod-engine-minio-volume:
    name: 'nestjs-mod-engine-minio-volume'
  nestjs-mod-engine-redis-volume:
    name: 'nestjs-mod-engine-redis-volume'
# docker system prune --all
# docker compose -f ./docker-compose-full.yml --env-file ./docker-compose-full.env --compatibility up -d
# docker compose -f ./docker-compose-full.yml --env-file ./docker-compose-full.env --compatibility up -d --no-build
